services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo_network
    restart: always  # Added for automatic restart

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  
      - "15672:15672" 
    networks:
      - odoo_network
    restart: always  # Added for automatic restart

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8069:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - ./config:/etc/odoo  # Keep this!
      - odoo-web-data:/var/lib/odoo/web/static
      - ./data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - RABBITMQ_HOST=rabbitmq  
    networks:
      - odoo_network
    restart: always  # Added for automatic restart

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo_network:
    driver: bridge